# Generated by Django 4.2.2 on 2023-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_primary_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emb_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Embroidery Price ($)'),
        ),
    ]
