# Generated by Django 4.2.2 on 2023-08-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_pricetypes_pricetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='types',
        ),
        migrations.AddField(
            model_name='productprice',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.pricetype'),
        ),
    ]
